README.md, package-lock.json, package.json, src/rest/transport/request.ts, src/websockets/crypto/index.ts, src/websockets/forex/index.ts, src/websockets/stocks/index.ts, src/websockets/transport/index.ts
This PR removes the dependency on several node-only modules in favor of cross-platform compatible alternatives. This will allow the library to be used in both browser and React Native environments. Specifically, this PR replaces the following modules:
|Old module|New module|
|------------|------------|
|`https` (node builtin)|[`cross-fetch`](https://www.npmjs.com/package/cross-fetch)|
|`ws`|[`websocket`](https://www.npmjs.com/package/websocket)\*|
|`querystring` (node builtin)|[`query-string`](https://www.npmjs.com/package/query-string)|
\* Note: Replacing `ws` with `websocket` introduces a breaking change which has been noted in the README.
Fixes #8 and #9.
=> Added browser + React Native support

package-lock.json, package.json, src/rest/stocks/index.test.ts, src/rest/stocks/lastQuoteForSymbol.ts, src/rest/stocks/lastTradeForSymbol.ts
Upgrades stock's LastTradeForSymbol and LastQuoteForSymbol to v2 endpoints.
Fixes issue https://github.com/polygon-io/client-js/issues/44
Note: This will be a major version bump given the breaking changes in the response.
=> Upgrades stock's LastTrade and LastQuote to v2 endpoints

src/rest/reference/index.ts
According to the documentation, as well as testing the return value, the return type of `tickerNews` should be an object with an array of `results`, not an array itself. The `TickerNews` shape is correct.
https://polygon.io/docs/stocks/get_v2_reference_news
=> Fix tickerNews return type

src/rest/stocks/lastQuote.ts
**The return type of property "results" of the Interface "ILastQuote" should not be an array according to the documentation.**
```
export interface ILastQuote {
request_id?: string;
status?: string;
results?: ITradeInfo[]; // => results?: ITradeInfo ;
}
```
=> Change return type for ITradeInfo in lastQuote.ts

package-lock.json, package.json, src/rest/reference/dividends.ts, src/rest/reference/marketHolidays.ts, src/rest/reference/optionsContracts.ts, src/rest/reference/stockFinancials.ts, src/rest/reference/stockSplits.ts, src/rest/reference/tickerNews.ts, src/rest/reference/tickers.ts, src/rest/stocks/trades.ts, src/rest/transport/request.ts
- Remove the erroneously added `object` type option for the IPolygonQuery interface
- Update all interfaces with map-like type queries
=> Correct erroneously added type option for map-like query structures 

src/rest/stocks/trades.ts
According to Trades documentation at https://polygon.io/docs/stocks/get_v3_trades__stockticker , the API supports query parameters starting _timestamp_, not _timestamp_.
=> Fixes incorrect payload attributes in ITradesQuotesQuery

src/rest/stocks/trades.ts
According to https://polygon.io/docs/stocks/get_v3_trades__stockticker and according to responses coming from Polygon API, trades response returns parameter **status**, not **success**.
=> Fixes incorrect payload attribute in ITrades

src/rest/reference/optionsContract.ts
Update `results?` interface to expect an object instead of an object array. 
Zenhub Ticket: [835](https://app.zenhub.com/workspaces/front-end-6041273131e20d0011cb88dc/issues/polygon-io/frontend/835)
[client-js GitHub issue](https://github.com/polygon-io/client-js/issues/95)
Customer pointed out inconsistency between our docs, and the code.
Compared against documentation. [Options Contract](https://polygon.io/docs/options/get_v3_reference_options_contracts__options_ticker)
=> fix: correct 'results?' to expect object instead of object array

src/rest/reference/index.ts
Update `dividends`, `stockSplits`, and `stockFinancials` methods found on the `IReferenceClient` interface with optional query params.
Zenhub Ticket: [834](https://app.zenhub.com/workspaces/front-end-6041273131e20d0011cb88dc/issues/polygon-io/frontend/834)
GitHub user issue #96
Addressing user GitHub issue.
=> fix: add optional query params

src/rest/crypto/snapshots.ts
The interface `SnapshotInfo` currently defines a field `todayChangePerc` which I believe is a typo and should be `todaysChangePerc`.
https://polygon.io/docs/crypto/get_v2_snapshot_locale_global_markets_crypto_tickers
=> Fix crypto `SnapshotInfo` field name

src/rest/stocks/summaries.ts
Fixed type on `ISession` interface on the summaries endpoint.
[#120](https://github.com/polygon-io/client-js/issues/120)
Requested change from launchpad user.
Through inbuilt testing suite to verify endpoints where being called correctly.
=> fix: incorrect type spelling for summaries session value

src/rest/crypto/index.test.ts, src/rest/forex/index.test.ts, src/rest/options/index.test.ts, src/rest/stocks/index.test.ts, src/rest/transport/request.ts
When the fetch call results in a Rejected Promise, catch the error and re-throw so that it bubbles up correctly and doesn't trigger a global unhandledrejection event. 
This is related to Issue #131.
=> Catch Rejected Promise and Throw Explicit Error

src/rest/reference/stockFinancials.ts
`source_filling_url ` and `filling_date ` field names are used incorrectly.
Ref: https://github.com/polygon-io/client-js/issues/141
=> fix: incorrect stock financials field usages #141

.gitignore, package-lock.json, package.json, tsconfig.json
I looked at several different methods of supporting dual formats, and introducing a bundler seems to be the only option right now. This PR adds the `tsup` package to our build, which allows us to bundle into both CJS and ESM. By default, it outputs to the dist directory which seems more standard than the lib directory that we were using, so I've updated configs to look at dist instead of lib. I'm using the package.json 'exports' functionality to route import and require to the right place, this should be supported in our target node versions.
=> Support Dual Module Formats (CommonJS and ESM)

package.json, src/rest/index.ts, src/rest/transport/request.ts
I updated the Launchpad header type definitions to fix the reported issue with partial Records. I also added an export of the requests file from index so that types defined in requests are included in the type definition bundle, and made all Launchpad headers optional to support Launchpad Metered.
Closes #157
=> Update header types and export types from request file

src/rest/crypto/snapshots.ts, src/rest/forex/snapshots.ts, src/rest/stocks/snapshots.ts
Updated snapshot minute to support timestamp and number of transactions. Snapshots for stocks, forex, and crypto have been updated to support `t` and `n`. You can test this out via the [website docs](https://polygon.io/docs/stocks/get_v2_snapshot_locale_us_markets_stocks_tickers).
=> Update snapshot min to support n and t

README.md
Depends on https://github.com/polygon-io/client-js/pull/164.
Added a new sections to the README.md file to explain the trace and pagination options. This debug mode prints the request URL, request headers, and response headers for each API call, providing invaluable information for debugging and understanding API interactions. The pagination function will automatically fetch all pages of data when the API response indicates more data is available.
=> Update README with pagination and trace modes

src/rest/transport/request.ts
This PR introduces improvements around request tracing and pagination, although distinct, I chose to bundle them into a single PR due to their interrelatedness. When dealing with APIs returning paginated results, figuring out what urls are being fetched becomes pretty complex without added logging. So, just adding the request tracing feature alongside pagination support, greatly simplifies the debugging -- that's why you see the two improvements in one PR. We added tracing to the python client already and will do the same for Go. So, this adds consistency too.
**Request Tracing**: A new optional `trace` parameter in `globalOptions` enables request and response logging for debugging purposes. When activated, the request URL, sanitized headers, and response headers are logged in the …
=> Added request tracing and API pagination support

src/rest/reference/marketStatus.ts
CBOE recently added the CGI (CBOE Global Indices) feed, and as a result it was added to the Market Status endpoint.
=> Add CGI to IIndicesGroups

src/rest/universal/universalSnapshot.ts
First commit Closes #200 
Issue:
The universal snapshot endpoint returns a `last_quote` field, which subsequently should have `ask_exchange` and `bid_exchange` fields for asset classes like Forex. See example api call:
`https://api.polygon.io/v3/snapshot?ticker.any_of=C:USDJPY&limit=1&apiKey=...`
```
{
"results": [
{
"market_status": "open",
"name": "United States dollar - Japanese yen",
"ticker": "C:USDJPY",
"type": "fx",
"session": {
"change": -1.35,
"change_percent": -0.929,
"close": 144.004,
"high": 145.551,
"low": 143.994,
"open": 145.361,
"volume": 172978,
"previous_close": 145.36
},
"last_quote": {
"last_updated": 1725469522000000000,
"timeframe": "REAL-TIME",
"ask": 144.02,
"ask_exchange": 48,
"bid": 144.01,
"bid_exchange": 48,
"exchange": 48
}
}
]
}
```
Second commit closes #191 …
=> Add Missing Fields for Universal Snapshots

src/rest/reference/stockFinancials.ts
As documented here: https://polygon.io/docs/stocks/get_vx_reference_financials
The `timeframe` parameter in stock financials endpoint has three possible values: annual, quarterly, and ttm
But JS client has no support for `ttm` option. This PR fixes it.
=> fix: missing timeframe `ttm` in stock financials

src/rest/reference/marketStatus.ts
As documented here: https://polygon.io/docs/stocks/get_v1_marketstatus_now
The response has `afterHours` property but JS client has a typo and looks for `afterhours` in the response. Thus, its value is returned as undefined. This PR fixes it.
=> fix: market status `afterhours` typo

scripts/generate-examples-with-tokens.js
Here's the script to generated the examples and the tokenized examples for the ui-docs-v2.
It takes in the openapi.json file and generates the js examples. This needs to be the cleaned openapi.json where we're fixing the operatorid's just so the functions map 1-1 in the client to the examples:
```
$ node generate-examples-with-tokens-new2.js
✅ Generated snippet: examples/get_benzinga_v1analyst_insights.js
✅ Generated snippet: examples-tokenized/get_benzinga_v1analyst_insights.js
✅ Generated snippet: examples/get_benzinga_v1analysts.js
✅ Generated snippet: examples-tokenized/get_benzinga_v1analysts.js
✅ Generated snippet: examples/get_benzinga_v1consensus_ratings.js
✅ Generated snippet: examples-tokenized/get_benzinga_v1consensus_ratings.js
✅ Generated snippet: …
```
=> Add generate-examples-with-tokens.js

src/main.ts
refactor: isolate axios instance to prevent global interceptor side effects
- fixes bug in Polygon client library where subsequent calls return `undefined` even though the network request succeeds
- first fetch works and renders as expected
- subsequent fetches retrieve data from API successfully (verified in browser network inspector), but API returns `undefined`
https://linear.app/mod-labs/issue/DVX-889/dev-fix-bug-w-subsequent-fetches-in-client-js-library
- discovered while testing API w/ demo — [see gist for code example](https://gist.github.com/penelopus/419ecb42fc4673ec21fb0537fa23db74)
bugfix
tested locally w/ fix
- with this branch, run `npm pack` to generate a *.tgz
- in sample project (using gist referenced above), link to local package w/ `npm install <path_to_tgz>`
- verify …
=> [DVX-889] isolate axios instance to prevent global interceptor side effects

package-lock.json, package.json, src/websockets/futures/index.ts, src/websockets/index.ts
For Business users and futures websocket connections, the exchange is required
- this PR extends support for an optional exchange parameter
https://linear.app/mod-labs/issue/DVX-919/dev-client-js-support-futures-business-connex-add-market-support
extended feature support
locally, and tested/verified w/ internal tool using alpha build
=> [DVX-919] support exchanges for Business futures websockets — v8.2.0 alpha
